import {RoleObject, EmojiObject, Sticker} from '../../../constants'

export default interface IGuildStructure {
    id: string,
    name: string,
    icon: string | null,
    iconUrl: string | null,
    icon_hash?: string | null,
    splash: string | null,
    discovery_splash: string | null,
    owner_id: string,
    permissions?: string,
    region?: string | null,
    afk_channel_id: string | null,
    afk_timeout: number,
    widget_enabled?: boolean,
    widget_channel_id?: string | null,
    verification_level: number,
    default_message_notifications: number,
    explicit_content_filter: number,
    roles:RoleObject[],
    emojis:EmojiObject[],
    features:["ANIMATED_ICON" | "VERIFIED" | "NEWS" | "VANITY_URL" | "DISCOVERABLE" | "MORE_EMOJI" | "INVITE_SPLASH" | "BANNER" | "COMMUNITY"],
    mfa_level: number,
    application_id: number | null,
    system_channel_id: number | null,
    system_channel_flags: number,
    rules_channel_id: number | null,
    max_presences?: number | null,
    max_members?: number,
    vanity_url_code: string | null,
    description: string | null,
    banner: string | null,
    premium_tier: number,
    premium_subscription_count?: number,
    preferred_locale: string,
    public_updates_channel_id: string | number,
    max_video_channel_users?: number,
    approximate_member_count?: number,
    approximate_presence_count?: number,
    welcome_screen?: {
        description: string | null,
        welcome_channels: {
            channel_id: string | null,
            description: string,
            emoji_id: string | null,
            emoji_name: string | null
        }[],
    },
    nsfw_level: number,
    stickers?: Sticker[],
    premium_progress_bar_enabled: boolean
}