export const OPCODE = {
  ZERO: 0,
  ONE: 1,
  TWO: 2,
  THREE: 3,
  FOUR: 4,
  FIVE: 5,
  SIX: 6,
  SEVEN: 7,
  EIGHT: 8,
  NINE: 9,
  TEN: 10,
  ELEVEN: 11,
  TWELVE: 12,
};

const INTENTS_OPTIONS = {
  GUILDS: 1 << 0,
  GUILD_MEMBERS: 1 << 1,
  GUILD_BANS: 1 << 2,
  GUILD_EMOJIS_AND_STICKERS: 1 << 3,
  GUILD_INTEGRATIONS: 1 << 4,
  GUILD_WEBHOOKS: 1 << 5,
  GUILD_INVITES: 1 << 6,
  GUILD_VOICE_STATES: 1 << 7,
  GUILD_PRESENCES: 1 << 8,
  GUILD_MESSAGES: 1 << 9,
  GUILD_MESSAGE_REACTIONS: 1 << 10,
  GUILD_MESSAGE_TYPING: 1 << 11,
  DIRECT_MESSAGES: 1 << 12,
  DIRECT_MESSAGE_REACTIONS: 1 << 13,
  DIRECT_MESSAGE_TYPING: 1 << 14,
  MESSAGE_CONTENT: 1 << 15,
  GUILD_SCHEDULED_EVENTS: 1 << 16,
  AUTO_MODERATION_CONFIGURATION: 1 << 20,
  AUTO_MODERATION_EXECUTION: 1 << 21,
};
export const INTENTS = {
  GUILDS: INTENTS_OPTIONS.GUILDS,
  GUILD_MEMBERS: INTENTS_OPTIONS.GUILD_MEMBERS,
  GUILD_BANS: INTENTS_OPTIONS.GUILD_BANS,
  GUILD_EMOJIS_AND_STICKERS: INTENTS_OPTIONS.GUILD_EMOJIS_AND_STICKERS,
  GUILD_INTEGRATIONS: INTENTS_OPTIONS.GUILD_INTEGRATIONS,
  GUILD_WEBHOOKS: INTENTS_OPTIONS.GUILD_WEBHOOKS,
  GUILD_INVITES: INTENTS_OPTIONS.GUILD_INVITES,
  GUILD_VOICE_STATES: INTENTS_OPTIONS.GUILD_VOICE_STATES,
  GUILD_PRESENCES: INTENTS_OPTIONS.GUILD_PRESENCES,
  GUILD_MESSAGES: INTENTS_OPTIONS.GUILD_MESSAGES,
  GUILD_MESSAGE_REACTIONS: INTENTS_OPTIONS.GUILD_MESSAGE_REACTIONS,
  GUILD_MESSAGE_TYPING: INTENTS_OPTIONS.GUILD_MESSAGE_TYPING,
  DIRECT_MESSAGES: INTENTS_OPTIONS.DIRECT_MESSAGES,
  DIRECT_MESSAGE_REACTIONS: INTENTS_OPTIONS.DIRECT_MESSAGE_REACTIONS,
  DIRECT_MESSAGE_TYPING: INTENTS_OPTIONS.DIRECT_MESSAGE_TYPING,
  MESSAGE_CONTENT: INTENTS_OPTIONS.MESSAGE_CONTENT,
  GUILD_SCHEDULED_EVENTS: INTENTS_OPTIONS.GUILD_SCHEDULED_EVENTS,
  AUTO_MODERATION_CONFIGURATION: INTENTS_OPTIONS.AUTO_MODERATION_CONFIGURATION,
  AUTO_MODERATION_EXECUTION: INTENTS_OPTIONS.AUTO_MODERATION_EXECUTION,
  ALL:
    INTENTS_OPTIONS.AUTO_MODERATION_CONFIGURATION |
    INTENTS_OPTIONS.AUTO_MODERATION_EXECUTION |
    INTENTS_OPTIONS.DIRECT_MESSAGES |
    INTENTS_OPTIONS.DIRECT_MESSAGE_REACTIONS |
    INTENTS_OPTIONS.DIRECT_MESSAGE_TYPING |
    INTENTS_OPTIONS.GUILDS |
    INTENTS_OPTIONS.GUILD_BANS |
    INTENTS_OPTIONS.GUILD_EMOJIS_AND_STICKERS |
    INTENTS_OPTIONS.GUILD_INTEGRATIONS |
    INTENTS_OPTIONS.GUILD_INVITES |
    INTENTS_OPTIONS.GUILD_MEMBERS |
    INTENTS_OPTIONS.GUILD_MESSAGES |
    INTENTS_OPTIONS.GUILD_MESSAGE_REACTIONS |
    INTENTS_OPTIONS.GUILD_MESSAGE_TYPING |
    INTENTS_OPTIONS.GUILD_PRESENCES |
    INTENTS_OPTIONS.GUILD_SCHEDULED_EVENTS |
    INTENTS_OPTIONS.GUILD_VOICE_STATES |
    INTENTS_OPTIONS.GUILD_WEBHOOKS |
    INTENTS_OPTIONS.MESSAGE_CONTENT,
};
export interface BotCordOptions {
  intents: number[];
}

export interface ClientInfo {
  verified: boolean | null,
  username: string | null,
  mfa_enabled: boolean | null,
  id: string  | null,
  flags: number  | null,
  discriminator: string  | null,
  bot: boolean  | null,
  avatarUrl: string  | null,
  avatarCode: string  | null,
  nameWithTag: string | null
  guilds: { 
    channels: any[]  | null,
    emojis: any[]  | null,
    roles: any[]  | null,
    users: any[]  | null,
    features: string[]  | null,
    stickers?: any[] | null,

 },
}

export const ACTIVITY_TYPE = {
    "PLAYING": 0,
    "STREAMING": 1,
    "LISTENING": 2,
    "WATCHING": 3,
    "CUSTOM": 4,
    "COMPETING": 5,
}

export interface IprovideStatus {

        since?: null ,
        activities: {
            name: string,
            type: number,
            url?: string
        }[],
        status:'online' | 'dnd' | 'idle' | 'invisible' | 'offline',
        afk: boolean
    
}

export const API_VERSION = 'v10'
export const APi_URL = "https://discord.com/api"